image: selenium/hub
pipelines:
  default:
   - step:
        services:
          - docker
        script:
          # Run Test
          - mvn test
          - docker ps

        artifacts: # defining the artifacts .
          - target/*